services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nytris\Bundle\Boost\Initialiser:
        # Arguments will be populated by NytrisExtension, if configured.
        public: true
